INIT_MLFF_LAUNCH_FUNCTION = "dpmoire_run_vasp"
INIT_MLFF_RUN_MARKER = "# DPMOIRE-LITE:RUN"
INIT_MLFF_RUN_MARKER_LINE = (
    f"{INIT_MLFF_LAUNCH_FUNCTION} {INIT_MLFF_RUN_MARKER}"
)
INIT_MLFF_SUBMIT_ADAPTER_SCHEMA = "dpmoire-lite.init-submit-adapter.v1"
