#!/bin/bash

#SBATCH -J MoTe2
#SBATCH -p batch
#SBATCH -N 1 --ntasks-per-node=64
#SBATCH --time=2-0:0:0
##SBATCH --mem=224GB
##SBATCH -d afterok:287
#SBATCH -o out.%j
#SBATCH -e err.%j

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export FI_PROVIDER=verbs
export UCX_NET_DEVICES=mlx5_0:1

module load oneapi-2022/hdf5-1.14.3
module load oneapi-2022/libxc-6.2.2
module load oneapi-2022/dftd4-3.6.0

mpirun  /gpfs/home/cwang/bin/vasp641c-ol > sout
